name: ZELDE
favicon: null
layout_spectrum: 0.9713578657247126
typography_spectrum: 0.5497195043135434
title: Zelde
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75705461-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a1a1a1'
    - '#e0e2e1'
    - '#0f0f0f'
    - '#32373a'
    - '#815b49'
  brandStrength: 0.375
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
